### ISSUE TITLE
Downloading PHP files instead of Executing them.

### ISSUE THREAD

**Issue by veroarts** [Servers-for-Hackers/ansible-nginx#1]
Hey fideloper,

I've been playing around with ansible for a bit and I'm using your playbooks. I'm using this playbook as well as your [PHP](https://github.com/Servers-for-Hackers/ansible-php-fpm) playbook.

I ran the playbooks successfully today, so I have the most recent code. My site is working as expected except when it comes to a PHP script. Rather than being executed, the file is being downloaded.

I haven't made any other customizations (except for the server / sitenames) to any of the scripts. Not sure if maybe you were getting the same issue and solved it somehow.

Thanks!

**Comment by veroarts** [comment]
I actually just changed the location of the php block inside my nginx config and all is well.

```
location ~ \.php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
    include fastcgi.conf;
    fastcgi_param DOCUMENT_ROOT /{{ domain }}/public;
    fastcgi_param SCRIPT_FILENAME /{{ domain }}/public$fastcgi_script_name;
    fastcgi_param APPENV {{ app_env }};
}
```

Thanks for making all this stuff available! It's been extremely helpful while learning Ansible.

ps:
I love the Chrooting PHP stuff.

**Comment by fideloper** [comment]
Hey! I didn't know anyone was paying attention to these :D

These are slowly getting more specific for my use case (for better of
worse) - and I e been hacking away at them this weekend. The Ansible-php
repository here will go in conjunction with it. Note that it does some
pretty specific things for chroot (when I push it up :D), now including
ensuring the /Dev/random stuff is available, and some files related to
timezone settings

(Chroot is turning out to be a major PITA, but when it comes together,
it'll be pretty nice!)

I push up the php stuff shortly as well. I have a PostgreSQL Ansible role
to publish too...

Glad it's been useful!

**Comment by fideloper** [comment]
Sorry for the terrible English, typing on ios is the worst :P
